const Discord = require("discord.js"); 
const config = require("../config.json");

const embed = new Discord.MessageEmbed()
    .setTitle(`Here's a list of the commands I can respond to'`)
    .addField('**Roles**', '!She, !He, !Them, !GameNight, !Alerts')
    .addField('**HelpCommand**', '!Help, !Report, !Support')
    .addField('', 'Just a heads up you will need to let users from the server message you otherwise some of my functionalities will not work')
    .setFooter('Automatically generated by Larsus')
    .setTimestamp()
    .setThumbnail('https://i.imgur.com/MpAKruf.png')
    .setColor('#1dca70')

module.exports = (embed);