const Discord = require("discord.js"); 
const config = require("../config.json");

const embed = new Discord.MessageEmbed()
    .setTitle('Welcome to the server!')
    .setDescription('Hello there and welcome to the Lizard Appreciation Club! \n \n Before I give you access to the server I am going to need you to check out the server-rules and make sure you understand and agree to these. \n \n Follow the instructions in the chat there and I will be giving you access to the server!')
    .setFooter('Automatically generated by Larsus')
    .setTimestamp()
    .setThumbnail('https://i.imgur.com/jP6nihO.png')
    .setColor('#1dca70')

module.exports = (embed);